language: python
python: 3.8
sudo: true
addons:
  apt:
    packages:
    - enchant
env:
# See https://pytest-cov.readthedocs.io/en/latest/plugins.html for why we set
# these variables.
- COV_CORE_CONFIG=.coveragerc
- COV_CORE_SOURCE=src
- COV_CORE_DATAFILE=.coverage.eager
before_install:
- travis_retry pip install --upgrade pip setuptools
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
script:
- make lint
- pytest -vvv --exitfirst --cov-append --cov-fail-under 100 tests/ --cov src --cov tests
after_success:
- codecov
