language: python
python: 3.8
sudo: true
addons:
  apt:
    packages:
    - enchant
before_install:
- travis_retry pip install --upgrade pip setuptools
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
script:
- make lint
# We do not require 100% coverage because of an issue collecting coverage.
# See https://github.com/pytest-dev/pytest-cov/issues/372.
- pytest -vvv --exitfirst tests/ --cov src --cov tests
after_success:
- codecov
